---
apiVersion: v1
kind: Service
metadata:
  name: grafana-serv
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/address-pool: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana-app
  ports:
    - port      : 3000
      targetPort: 3000
      protocol  : TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-depl
  labels:
    app: grafana-app
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name           : grafana
        image          : grafana
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
...
