---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-serv
  labels:
    app: influxdb-app
spec:
  type: ClusterIP
  selector:
    app: influxdb-app
  ports:
    - port      : 8086
      targetPort: 8086
      protocol  : TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-depl
  labels:
    app: influxdb-app
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
        - name           : influxdb
          image          : influxdb
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name     : influxdb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
...
