---
apiVersion: v1
kind: Service
metadata:
  name: mysql-serv
  labels:
    app: mysql-app
spec:
  type: ClusterIP
  selector:
    app: mysql-app
  ports:
    - port: 3306

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
  labels:
    app: mysql-app
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name           : mysql
          image          : mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts:
            - name         : mysql-persistent-storage
              mountPath    : /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
...
