---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-serv
  labels:
    app: wordpress-app
  annotations:
    metallb.universe.tf/address-pool: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress-app
  ports:
    - port      : 5050
      targetPort: 5050
      protocol  : TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-depl
  labels:
    app: wordpress-app
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name           : wordpress
          image          : wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
...
